---
title: ESMA 3015 - Elementary Statistics
header-includes: \usepackage{color}
output:
  html_document: default
  pdf_document:
    fig_caption: no
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
whichcomp <- strsplit(getwd(),"/")[[1]][3]
load(paste0("c:/users/", whichcomp, "/Dropbox/teaching/Resma3/Resma3.RData"))
require(knitr)
require(ggplot2)
require(grid)
```
`r hl()$basefontsize()`

[Resma3.RData](../Resma3/Resma3.RData?Ver3.1) (Ver 3.1)

For a nice introduction to Statistics watch the PBS-NOVA episode [Prediction by the Numbers](http://www.pbs.org/video/prediction-by-the-numbers-hg2znc/)

## 1 General Information   

1.1. [Syllabus](syl.html)  


## 2 Some Basic Ideas and Concepts

2.1.  [Introduction to ESMA 3015](intro.html)  
2.2.  [Data Collection](collect.html)

## 3 Computer and R

3.1.  [Installation and Troubleshooting](../Resma3/computerandR.3015.html)  
3.2   [Basic R commands](../Resma3/basic.R.commands.3015.html)  
3.3.  [Short List of Important R commands](../Resma3/short.list.commands.html)    
3.4.  [R routines](../Resma3/routines.html)  
3.5.  [Resma3 vs base R](../Resma3/baseR.html)

## 4 Descriptive Statistics

4.1.  [Categorical Data](categorical.html)  
4.2.  [Quantitative Data](quantitative1.html)  
4.3.  [Percentiles and Boxplots](quantitative2.html)  
4.4.  [Two Quantitative Variables - Correlation](correlation1.html)   
4.5.  [Outliers](outlier.html)   
4.6.  [Exercise Problems](exercise1.html)  

## 5 Probability

5.1.  [Introduction to Probability](probbasic.html)  
5.2. [Normal Distribution and the Central Limit Theorem](normal.html)  
5.3.  [Checking for Normality](normalcheck.html)  
5.4.  [Exercise Problems](exercise2.html)

## 6 Statistical Inference

6.1.  [Population - Sample](popsample.html)  
6.2.  [Estimation - Confidence Interval](estimation.html)  
6.3.  [Hypothesis Testing](hyptest.html)  
6.4.  [The Lady Tasting Tea](lady-tea.html)  
6.5.  [Inference for the Mean $\mu$](mean.html)  
6.6.  [Inference for a Proportion $\pi$](prop.html)  
6.7.  [Bayesian Inference](bayes.html)  
6.8.  [Exercise Problems](exercise3.html)

## 7 Correlation and Regression

7.1.  [Correlation](correlation2.html)  
7.2.  [Regression](regression.html)  
7.3.  [Exercise Problems](exercise4.html)



